---
  - name: Check if vsts agent path exists
    stat: path={{ vsts_agentfolder }}
    register: vsts_agentfolder_result
    failed_when: vsts_agentfolder_result is not defined
    ignore_errors: yes

  - name: Unconfigure vsts-agent
    command: "./config.sh remove --unattended --auth PAT --token $VSTS_ACCESSTOKEN"
    args:
      chdir: "{{vsts_agentfolder}}"
    environment:
      VSTS_ACCESSTOKEN: "{{ vsts_accesstoken }}"
    become_user: "{{vsts_agent_user}}"
    when: vsts_agentfolder_result.stat.exists
    no_log: true
    tags:
      - unconfig
  
  - name: Remove vsts-agent folders
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - "{{ vsts_agentfolder }}"
      - "{{ vsts_workfolder }}"
    become: true
  
  - name: Check if vsts agent service exists
    stat: path=/etc/systemd/system/vsts-agent.service
    register: vsts_service_result
    failed_when: vsts_service_result is not defined
    ignore_errors: yes

  - name: Disable vsts-agent systemd service
    service:
      name: vsts-agent
      enabled: no
      state: stopped
    become: true
    when: vsts_service_result.stat.exists
    tags:
      - service
      - unconfig

  - name: Remove vsts-agent systemd service file
    file:
      path: /etc/systemd/system/vsts-agent.service
      state: absent
    become: true
    when: vsts_service_result.stat.exists
  
  - name: Include user tasks
    include_tasks: common/user.yml
    when: dryrun is not defined